name: gnrllybttr_sidebar_example
description: "An example usage of the GnrllyBttrSidebar package"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^6.1.1
  flutter:
    sdk: flutter

  gnrllybttr_sidebar:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
